{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3397, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_40415/762650610.py\", line 24, in <cell line: 24>\n",
      "    from tta_learner import Learner\n",
      "  File \"/media/philipp/ssd1_2tb/nax_projects/super_resolution/TTA_SR/code/jupyter/../tta_learner.py\", line 3, in <module>\n",
      "    from tta_sr import TTASR\n",
      "  File \"/media/philipp/ssd1_2tb/nax_projects/super_resolution/TTA_SR/code/jupyter/../tta_sr.py\", line 12, in <module>\n",
      "    from tta_model.network_swinir import define_model\n",
      "  File \"/media/philipp/ssd1_2tb/nax_projects/super_resolution/TTA_SR/code/jupyter/../tta_model/network_swinir.py\", line 13, in <module>\n",
      "    from timm.models.layers import DropPath, to_2tuple, trunc_normal_\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/__init__.py\", line 2, in <module>\n",
      "    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \\\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/models/__init__.py\", line 1, in <module>\n",
      "    from .beit import *\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/models/beit.py\", line 32, in <module>\n",
      "    from .vision_transformer import checkpoint_filter_fn\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/models/vision_transformer.py\", line 35, in <module>\n",
      "    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD, IMAGENET_INCEPTION_MEAN, IMAGENET_INCEPTION_STD\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/data/__init__.py\", line 5, in <module>\n",
      "    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/data/dataset.py\", line 12, in <module>\n",
      "    from .parsers import create_parser\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/data/parsers/__init__.py\", line 1, in <module>\n",
      "    from .parser_factory import create_parser\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/data/parsers/parser_factory.py\", line 3, in <module>\n",
      "    from .parser_image_folder import ParserImageFolder\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/data/parsers/parser_image_folder.py\", line 10, in <module>\n",
      "    from timm.utils.misc import natural_key\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/utils/__init__.py\", line 13, in <module>\n",
      "    from .summary import update_summary, get_outdir\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/timm/utils/summary.py\", line 9, in <module>\n",
      "    import wandb\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/__init__.py\", line 26, in <module>\n",
      "    from wandb import sdk as wandb_sdk\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/__init__.py\", line 9, in <module>\n",
      "    from .wandb_init import _attach, init  # noqa: F401\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/wandb_init.py\", line 27, in <module>\n",
      "    from . import wandb_login, wandb_setup\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/wandb_login.py\", line 23, in <module>\n",
      "    from .wandb_settings import Settings, Source\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py\", line 38, in <module>\n",
      "    from wandb.sdk.wandb_setup import _EarlyLogger\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py\", line 28, in <module>\n",
      "    from . import wandb_manager\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py\", line 12, in <module>\n",
      "    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/sdk/lib/proto_util.py\", line 7, in <module>\n",
      "    from wandb.proto import wandb_internal_pb2 as pb\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py\", line 15, in <module>\n",
      "    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/wandb/proto/wandb_base_pb2.py\", line 36, in <module>\n",
      "    _descriptor.FieldDescriptor(\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/google/protobuf/descriptor.py\", line 560, in __new__\n",
      "    _message.Message._CheckCalledFromGeneratedFile()\n",
      "TypeError: Descriptors cannot not be created directly.\n",
      "If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\n",
      "If you cannot immediately regenerate your protos, some other possible workarounds are:\n",
      " 1. Downgrade the protobuf package to 3.20.x or lower.\n",
      " 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n",
      "\n",
      "More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 1992, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1118, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1012, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 865, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 818, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(r))\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 736, in format_record\n",
      "    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "  File \"/home/zk/miniconda3/envs/work/lib/python3.9/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "import copy\n",
    "import glob\n",
    "import json\n",
    "import os\n",
    "import shutil\n",
    "from datetime import datetime\n",
    "\n",
    "import ipdb\n",
    "import numpy as np\n",
    "import setGPU\n",
    "import torch\n",
    "import tqdm\n",
    "\n",
    "\n",
    "import sys\n",
    "  \n",
    "# setting path\n",
    "sys.path.append('..')\n",
    "\n",
    "\n",
    "from tta_data import create_dataset, create_dataset_for_image_agnostic_gdn\n",
    "import tta_util as util\n",
    "# from tta_sr_one_cycle import TTASR\n",
    "from tta_learner import Learner\n",
    "from tta_options import options\n",
    "# from DualSR import DualSR\n",
    "# from tta_sr import TTASR\n",
    "# from tta_sr_bicubic import TTASR\n",
    "from tta_sr_loss_ablation import TTASR\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.12 ('work')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "5f7424fba8be07a9551cbf6bef8432ad4fa6b64143fcf7b91371c938f3fc3511"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
